#6 Added possibility to provide custom guzzle options
softonic/graphql-client pull request #10
Opened 2018-02-07 09:50 UTC by duxthefux

This PR adds the possibility to provide custom guzzle options when using `ClientBuilder`.

This is essential if you have custom authorization methods, need to set cookies, headers, etc.

2018-02-07 16:34 UTC, rccrdpccl requested changes
Thanks for the contribution! I thing this change will add a lot to the repo. Would you mind adding a test for this?

I have also added some minor comments about style.

2018-02-07 16:34 UTC, rccrdpccl commented on src/ClientBuilder.php
> +	/**
This comment does not add anything to the type hint already in place.

2018-02-07 16:34 UTC, rccrdpccl commented on src/ClientBuilder.php
> +		// allow custom guzzle options
This comment does not add anything to the already well-named variable.

2018-02-07 16:47 UTC, duxthefux commented
hey, I've added two tests to run the ClientBuilder with $guzzleOptions (i used  "cookies" - option)
i also removed phpdocs again, as you are right, as it's redundant.

Kind regards

2018-02-07 19:44 UTC, rccrdpccl approved these changes

2018-02-07 19:45 UTC, merged

2018-02-07 19:46 UTC, rccrdpccl commented
Thanks!

2018-02-08 06:45 UTC, duxthefux commented
thanks for merging :-) would you mind creating a new release so I can use it in composer.json?

Thanks!

2018-02-08 07:11 UTC, rccrdpccl commented
Sure: https://github.com/softonic/graphql-client/releases/tag/1.1.0