Pass the transfer exception through as "previous"
softonic/graphql-client pull request #13
Opened 2018-05-04 09:00 UTC by jsandersuk

- Provides access to server response to help identify errors

2018-05-07 07:54 UTC, rccrdpccl requested changes
Thanks for your contribution! Could you please add a small test with an example of the case we are intending to cover here?

2018-05-08 09:04 UTC, jsandersuk commented
I have added a test to cover the suggested code change

2018-05-08 09:11 UTC, rccrdpccl approved these changes

2018-05-08 14:41 UTC, jsandersuk commented
If you're happy with the changes could you please merge them into master at your earliest convenience?

Thanks for your help

2018-05-08 15:18 UTC, joskfg requested changes

2018-05-08 15:18 UTC, joskfg commented on src/Client.php
> +            throw new \RuntimeException('Network Error.'.$e->getMessage(), null, $e);
The code is not right because the default is 0 not null, could you fix it? After this I'll merge the PR. Thanks!

2018-05-09 07:40 UTC, jsandersuk commented
You are indeed correct; I have updated the code to be "0" rather than NULL

2018-05-09 07:57 UTC, merged

2018-05-09 07:58 UTC, rccrdpccl commented
Thanks for your contribution!