Ability to change uri for query
softonic/graphql-client pull request #27
Opened 2019-09-25 13:17 UTC by 4n70w4

2019-09-25 13:41 UTC, rccrdpccl commented
Thanks for the contribution @4n70w4 .

Could you please explain your use case behind this, so that we could better understand?

Could you also please add a simple test case?

2019-09-25 14:16 UTC, 4n70w4 commented
@rccrdpccl example:

I reuse the already configured guzzle client and needs to define the endpoint for the request.

About the tests, this does not affect your library. Also does not create new mutants in mutation testing.

2019-09-25 14:34 UTC, rccrdpccl commented
Isn't this configurable by passing guzzle options to the client? I am curious to understand in what case you'd need to redefine request uri from already initialized client.

Tests are not only for the code that is already there, but it prevents future changes to break the functionality that you are introducing. However we can wait to define exact use case before writing tests.

2019-09-25 16:12 UTC, 4n70w4 commented
```php

use Softonic\GraphQL\Client;
use Softonic\GraphQL\Response;
use Softonic\GraphQL\ResponseBuilder;

....

    public function something(array variables, $query, $uri) : Response {
        $client = new Client($this->guzzle, new ResponseBuilder() );

        return $client->query($query, $variables, $uri);
    }

....

// another methods to use guzzle client for non graphql requests

```

2019-09-26 05:59 UTC, rccrdpccl commented
Thanks for the example. What is the reason for re-using guzzle client?

2019-09-26 09:22 UTC, joskfg commented
Thanks @4n70w4 for your PR!

I think add the uri in the query call could be not the best option. We could find a better solution if we know the exact use case to do something cleaner if it is possible.

If the case is to access two different graphql servers I think that the best option is to create two clients. This make sense because probably the clients should have different options. For example, the authentication could be different.

2019-09-26 10:20 UTC, 4n70w4 commented
In your opinion hardcode uri as a blank line is the best option?

2019-09-26 10:25 UTC, 4n70w4 commented
@rccrdpccl I already have a configured client (authorization, certificates, proxies, etc.) for access to the provider’s endpoints. I see no reason to configure another client with a difference only in the url '/ graphql'.

2019-09-26 13:15 UTC, rccrdpccl commented
@4n70w4 Ok, thanks for explaining, it seems a reasonable use case. I think your approach it's a good improvement for the library, ideally we should end up with something like `public function query(string $query, array $variables = null, string $uri = '', array $options = []): Response`, but for now we can add parameter `$uri` and leave options to be added in the near future.

I will add a few small comments to the PR so we can get it merged as soon as possible!

In order to solve this long term, we are planning to release `v2`, where we will need to configure the client in a similar fashion: `new Client($this->guzzle, new ResponseBuilder(), '/quert_endpoint', '/mutation_endpoint' );`. Would this work for your use case?

2019-09-26 13:17 UTC, rccrdpccl requested changes
Please do not forget to add tests, so that we make sure we will not have any regression on this behaviour in the future.

2019-09-26 13:17 UTC, rccrdpccl commented on src/Client.php
> +     * @param string $query
Code standards in this project are to not declare variables in annotations: we use type hinting instead, and use annotations only for exceptions that unfortunately cannot be declared in the function's signature. Could you please remove annotations for params and return value?

2019-09-26 13:17 UTC, rccrdpccl commented on src/Client.php
> +    public function query(string $query, array $variables = null, $uri = ''): Response
Could you please add type hinting to the newly added parameter?

2019-09-26 14:23 UTC, 4n70w4 commented
I already use my fork in production. I don’t know if it will be time to go back to this PR.

Such a design could also solve similar problems:

```php
new Client($this->guzzle, new ResponseBuilder(), '/endpoint');
```

2019-12-11 14:17 UTC, closed without merging

2019-12-11 14:18 UTC, rccrdpccl commented
Close for inactivity. If interested in implementing this issue, please re-open it or file an issue